//
//  MoofuslistImageNames.swift
//  moofuslist
//
//  Created by Lamar Williams III on 1/24/26.
//

actor ImageNames {
  private let imageNames: [String: [String]] = [
    "360-degree view": ["binoculars.fill"],
    "9/11 memorial": ["building.columns.fill"],
    "alcatraz": ["ferry.fill","binoculars.fill","figure.walk"],
    "arcade games": ["gamecontroller.fill"],
    "art": ["photo.artframe"],
    "art exhibits": ["paintpalette.fill"],
    "arts": ["photo.artframe"],
    "aquarium": ["fish.fill"],
    "aquariums": ["fish.fill"],
    "attractions": ["figure.walk"],
    "bakeries": ["birthday.cake"],
    "bars": ["wineglass.fill"],
    "beach": ["beach.umbrella.fill"],
    "beachs": ["beach.umbrella.fill"],
    "beauty salons": ["comb.fill"],
    "bike": ["bicycle"],
    "biking": ["bicycle"],
    "bridge": ["figure.walk"],
    "boat": ["ferry.fill"],
    "bookstore": ["books.vertical.fill","book.pages"],
    "bookstores": ["books.vertical.fill","book.pages"],
    "boutiques": ["handbag.fill"],
    "bowling": ["figure.bowling"],
    "brewery": ["cup.and.saucer.fill"],
    "butterfly exhibit": ["ant.fill", "ladybug.fill"],
    "cable car": ["cablecar.fill"],
    "cable cars": ["cablecar.fill"],
    "cafes": ["cup.and.saucer.fill"],
    "camping": ["tent.2.fill"],
    "cemetery": ["cross.fill"],
    "children's activities": ["figure.child"],
    "chinatown": ["chineseyuanrenminbisign","fork.knife","storefront.fill"],
    "clubs": ["figure.socialdance","music.note.house.fill"],
    "coit tower": ["binoculars.fill"],
    "colleges": ["graduationcap.fill"],
    "comedy clubs": ["person.wave.2.fill"],
    "concert hall": ["music.note.house.fill","music.note.list"],
    "concert halls": ["music.note.house.fill","music.note.list"],
    "dance clubs": ["figure.socialdance"],
    "dining": ["fork.knife"],
    "district": ["storefront.fill"],
    "drive": ["car.fill"],
    "education": ["text.book.closed.fill"],
    "empire state building": ["building.columns.fill", "binoculars.fill"],
    "entertainment": ["popcorn.fill"],
    "events": ["calendar"],
    "ferry": ["ferry.fill"],
    "farmers markets": ["leaf.arrow.trianglehead.clockwise"],
    "festival": ["party.popper.fill"],
    "fishing": ["figure.fishing"],
    "food": ["fork.knife"],
    "food trucks": ["truck.box.fill"],
    "funicular": ["cablecar.fill"],
    "galleries": ["photo.fill.on.rectangle.fill"],
    "garden": ["leaf.fill"],
    "gardens": ["leaf.fill"],
    "golf": ["figure.golf"],
    "graffiti": ["photo.artframe","theatermask.and.paintbrush.fill"],
    "gyms": ["dumbbell.fill"],
    "harbor": ["water.waves"],
    "haight-ashbury": ["figure.walk","binoculars.fill"],
    "healthcare": ["staroflife.shield.fill"],
    "health clinics": ["plus.circle.fill"],
    "hike": ["figure.hiking"],
    "hiking": ["figure.hiking"],
    "historic site": ["building.columns.fill"],
    "historical": ["building.columns.fill"],
    "hot air balloon festival": ["balloon.2.fill"],
    "innovation": ["lightbulb.max.fill"],
    "insect exhibit": ["ant.fill", "ladybug.fill"],
    "karaoke": ["music.mic","music.note.house.fill"],
    "lakes": ["water.waves"],
    "landmark": ["building.columns.fill"],
    "landmarks": ["building.columns.fill"],
    "library of congress": ["books.vertical.fill","building.columns.fill"],
    "libraries": ["books.vertical.fill"],
    "little havana": ["storefront.fill","fork.knife"],
    "lombard street": ["road.lanes.curved.right"],
    "lounges": ["sofa.fill"],
    "malls": ["building.2.fill"],
    "market": ["storefront.fill"],
    "massage": ["carseat.right.massage.fill"],
    "medical": ["cross.case.fill"],
    "movies": ["movieclapper.fill","ticket.fill"],
    "murals": ["paintpalette.fill"],
    "museum": ["building.fill"],
    "museums": ["building.2.fill"],
    "museum of art": ["photo.artframe","paintpalette.fill"],
    "music": ["music.pages.fill"],
    "musicals": ["music.note.house.fill"],
    "nature": ["leaf.fill"],
    "nightlife": ["figure.socialdance","moon.stars"],
    "observatory": ["building.columns.fill"],
    "observe": ["binoculars.fill"],
    "outdoor": ["sun.max.fill"],
    "outdoor walk": ["sun.max.fill","figure.walk"],
    "park": ["tree.fill"],
    "parks": ["tree.fill"],
    "photography": ["camera.fill"],
    "pizza": ["fork.knife"],
    "pubs": ["mug.fill"],
    "playgrounds": ["figure.play"],
    "racetrack": ["road.lanes.curved.right"],
    "railway": ["train.side.front.car"],
    "restaurants": ["fork.knife"],
    "scenic views": ["binoculars.fill"],
    "scenic walk": ["binoculars.fill","figure.walk"],
    "schools": ["long.text.page.and.pencil"],
    "science": ["atom"],
    "shop": ["storefront.fill"],
    "shopping": ["storefront.fill","bag.fill"],
    "shops": ["storefront.fill"],
    "sightseeing": ["binoculars.fill"],
    "sightseeing walk": ["binoculars.fill","figure.walk"],
    "skateparks": ["skateboard.fill"],
    "space": ["moon.stars.fill","globe.americas.fill"],
    "sports": ["figure.basketball"],
    "stairs": ["figure.stairs"],
    "state capitol": ["building.columns.fill"],
    "statue of liberty": ["ferry.fill","figure.walk"],
    "stroll": ["figure.walk"],
    "swimming": ["figure.open.water.swim"],
    "tennis": ["figure.tennis","tennis.racket"],
    "theater": ["theatermasks.fill"],
    "theaters": ["theatermasks.fill"],
    "theatre": ["theatermasks.fill"],
    "theme parks": ["ticket.fill"],
    "times square": ["theatermasks.fill","storefront.fill","person.2.badge.plus.fill"],
    "tour": ["figure.walk"],
    "trails": ["figure.hiking"],
    "travel": ["airplane"],
    "university": ["graduationcap.fill","books.vertical.fill","building.2.fill"],
    "yoga": ["figure.yoga"],
    "vibrant boardwalk": ["fork.knife","storefront.fill"],
    "views": ["binoculars.fill"],
    "walking": ["figure.walk.motion"],
    "waterfront": ["water.waves"],
    "wharf": ["water.waves"],
    "wildlife": ["pawprint.fill"],
    "zoo": ["pawprint.fill","tortoise.fill","bird.fill"],
    "zoos": ["pawprint.fill","tortoise.fill","bird.fill"]
  ]

  init() { }
  
  func process(input: String, result: inout [String]) -> [String] {
    for (key, imageStrings) in imageNames {
      if input.contains(key) {
        for imageString in imageStrings {
          if result.contains(imageString) { continue }
          result.append(imageString)
        }
      }
    }
    print("input=\(input) \(result)")
    return result
  }
}
